name: SpeakerDiarization
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.11.13
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - ffmpeg-python==0.2.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - future==1.0.0
      - idna==3.11
      - jinja2==3.1.6
      - llvmlite==0.45.1
      - markupsafe==2.1.5
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==2.3.4
      - openai-whisper==20250625
      - pandas==2.3.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.9.18
      - requests==2.32.5
      - six==1.17.0
      - sympy==1.14.0
      - tiktoken==0.12.0
      - torch==2.9.0+cu126
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
